# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
  


on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
          touch .env
          echo TOKEN = ${{ secrets.TOKEN }} >> .env
          echo CLIENTID = ${{ secrets.CLIENTID }} >> .env
          echo GUILDID = ${{ secrets.GUILDID }} >> .env
          echo MONGOURL = ${{ secrets.MONGOURL }} >> .env
          echo MONGOURLECONOMY = ${{ secrets.MONGOURLECONOMY }} >> .env
          echo MONGOURLBIRTHDAY = ${{ secrets.MONGOURLBIRTHDAY }} >> .env
          echo MONGOURLUSERS = ${{ secrets.MONGOURLUSERS }} >> .env
          echo MONGOURLTICKET = ${{ secrets.MONGOURLTICKET }} >> .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test

    - name: Run command and stop output
      id: condition
      run: | 
        ${"Client ready as Hydra!"}
        if[[ $output == *"Client ready as Hydra!"*]]
        echo "String found indicating successful run"
        exit 0
